version: '3'

services:
  digdag:
    build: ./digdag
    ports:
      - 65432:65432
      - 65433:65433
    volumes:
      - .:/opt/digdag
  mysql:
    build: ./mysql
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
